### PR TITLE
ADD: add MPL-Widget

### PR DESCRIPTION
**Pull request by kmuehlbauer**
-  add MPL-Widget
-  encapsulate RadolanCanvas and ColorBar into one RadolanWidget, rework city-marker

From this version we have "two"-backends "matplotlib" and "vispy". We shoudl implement all functions according to be usable with both backends (if possible).

### CODE REVIEW

**Comment by heistermann** [comment]
I tried this on my computer - the actual swapping between mpl and vispy is not yet implemented, right? Or should I already see it?

Anyway, We should pull this in and see it from there...

**Comment by kmuehlbauer** [comment]
Wait, I have some commits coming...

**Comment by kmuehlbauer** [comment]
@heistermann OK, we can pull this in. Works on my side. Keyboard 'c' will change between Widgets.

**Comment by heistermann** [comment]
Beautiful - works fine on my machine!

**Pull request merged**
