### PR TITLE
WIP: widgetify of property boxes

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- This converts the `sourcebox`, `mediabox` and `mousebox` into separate widgets.
- These widgets are subclassed from `DockWidget` which can have some common layout and properties.
- The box-widgets are added to the main gui
- The MenuBar is now child of the MainWindow and has `File`, `Tools` (the boxes) and `Help`
- The `Properties` are now just an QObject to hold common data.

Also added:
- [x] `DXCanvas` for display of polar data (DWD-DX)
- [x] add lon, lat conversion to `DXCanvas` for correct display in `mousebox`
- [x] PolarImage class, which handles the specific polar transform etc., by creating multiple instances we can have a radar mosaic (with some constraints to projection)
- [x] MPL PolarImage, but only as nonfunctional stub

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Everytime I look at it, it seems one could do it another way. Maybe we should decide for one layout and Window/Widgets behaviour and also where to put functions.

I thought it would be a good idea to have functions which are changing stuff in one box belong inside this box. But this might not be feasable all the time. There are still remains of some  assignments which need to be moved to another class.

**Comment by heistermann** [comment]
I agree that it's hard to decide. It is always a compromise between overcrowding the box and hiding stuff in the menu bar. Sorry I can't say anything too helpful right now. Merge as you see fit and we'll take it from there.

**Comment by kmuehlbauer** [comment]
Before this converts itself into a monster, I'll merge this when the MPL-Polar Stuff is implemented.

**Comment by kmuehlbauer** [comment]
I added mouse move functionality to MPLCanvas partly. X,Y is in polar stereographic projected coordinates and longitude/latitude isn't working correctly due to this. 

I'm not sure if we should just copy the glcanvas approach or how else we can do this. 

@heistermann Just merge this, if you are OK with the overall direction of this PR. We can tweak the other things from there with smaller PR's

**Comment by heistermann** [comment]
When I run the code, I am facing an error that appears to be related to OpenGL (caused via vispy).
`RuntimeError: Function glBindFramebuffer not present in context (OpenGL version is 1.1.0).`

Might just be that I need to update OpenGL...

I'll be caught up with a lot of stuff during the next days, so I'd be fine if we just merge and I'll try to fix this issue on my machine.

**Comment by kmuehlbauer** [comment]
> When I run the code, I am facing an error that appears to be related to OpenGL (caused via vispy).
> RuntimeError: Function glBindFramebuffer not present in context (OpenGL version is 1.1.0).
> 
> Might just be that I need to update OpenGL...

Yes, I think OPenGL version 2.1 is needed at least. So I'll pull this in and try to fix the Todos one by one.

**Pull request merged**
